# Generated by Django 6.0.6 on 2026-07-13 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_alter_class_unique_together'),
        ('payments', '0003_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='class_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_types', to='classes.class', verbose_name='Classe concernée'),
        ),
    ]
