# Generated by Django 6.0.6 on 2026-07-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_alter_class_unique_together'),
        ('payments', '0004_add_class_to_feetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feetype',
            name='class_assigned',
        ),
        migrations.AddField(
            model_name='feetype',
            name='class_assigned',
            field=models.ManyToManyField(blank=True, related_name='fee_types', to='classes.class', verbose_name='Classes concernées'),
        ),
    ]
