# Generated by Django 6.0.6 on 2026-07-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_feetype_class_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feetype',
            name='cycle',
            field=models.CharField(choices=[('all', 'Tous'), ('prescolaire', 'Préscolaire'), ('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée')], default='all', max_length=20),
        ),
    ]
