# Generated by Django 6.0.6 on 2026-07-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_feetype_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('partial', 'Partiel'), ('completed', 'Payé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20),
        ),
    ]
