# Generated by Django 6.0.4 on 2026-05-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('capacity', models.IntegerField(default=30)),
                ('room_type', models.CharField(choices=[('normal', 'Normale'), ('computer', 'Informatique'), ('laboratory', 'Laboratoire'), ('library', 'Bibliothèque')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Occupée'), ('maintenance', 'En maintenance')], default='available', max_length=20)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('equipment', models.TextField(blank=True, help_text='Liste des équipements')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['building', 'floor', 'name'],
            },
        ),
    ]
