# Generated by Django 6.0.4 on 2026-05-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='specialty',
            field=models.CharField(blank=True, choices=[('maths', 'Sciences Mathématiques'), ('experimental', 'Sciences Expérimentales'), ('sociales', 'Sciences Sociales'), (' lettres', 'Lettres'), ('none', 'Aucune')], default='none', max_length=20),
        ),
    ]
