# Generated by Django 6.0.4 on 2026-05-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_specialty'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='class',
            name='specialty',
            field=models.CharField(blank=True, choices=[('maths', 'Sciences Mathématiques'), ('experimental', 'Sciences Expérimentales'), ('sociales', 'Sciences Sociales'), ('lettres', 'Lettres'), ('none', 'Aucune')], default='none', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name', 'cycle', 'specialty', 'academic_year')},
        ),
    ]
