# Generated by Django 6.0.4 on 2026-05-12 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_update_unique_constraint_with_specialty'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='capacity',
            field=models.IntegerField(default=40, help_text="Capacité maximale d'élèves"),
        ),
        migrations.AddField(
            model_name='class',
            name='main_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classes', to='rooms.room'),
        ),
    ]
