# Generated by Django 6.0.4 on 2026-06-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_class_capacity_class_main_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='observation',
            field=models.TextField(blank=True),
        ),
    ]
