# Generated by Django 6.0.6 on 2026-06-30 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_add_prescolaire'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='name',
            field=models.CharField(choices=[('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('prescolaire', 'Préscolaire')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='cycle',
            unique_together={('name', 'tenant')},
        ),
    ]
