# Generated by Django 6.0.5 on 2026-07-11 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_class_tenant_cycle_tenant_scheduleentry_tenant_and_more'),
        ('tenants', '0003_remove_tenant_license_expiry_tenant_license_end_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name', 'cycle', 'specialty', 'academic_year', 'tenant')},
        ),
    ]
