# Generated by Django 6.0.6 on 2026-06-30 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'école")),
                ('subdomain', models.CharField(help_text='Ex: ecole-a (sera utilisé comme identifiant URL)', max_length=50, unique=True, verbose_name='Sous-domaine')),
                ('license_key', models.CharField(max_length=100, unique=True, verbose_name='Clé de licence')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_pending', models.BooleanField(default=True, help_text="Un nouveau tenant est en attente jusqu'à activation par le super admin", verbose_name="En attente d'activation")),
                ('license_expiry', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('max_users', models.IntegerField(default=10, verbose_name="Nombre max d'utilisateurs")),
                ('max_students', models.IntegerField(default=500, verbose_name="Nombre max d'élèves")),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('contact_phone', models.CharField(blank=True, max_length=15, verbose_name='Téléphone')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenants', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Client (établissement)',
                'verbose_name_plural': 'Clients (établissements)',
                'ordering': ['-created_at'],
            },
        ),
    ]
