# Generated by Django 6.0.6 on 2026-07-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_remove_tenant_max_students_remove_tenant_max_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='license_expiry',
        ),
        migrations.AddField(
            model_name='tenant',
            name='license_end',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin de licence'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='license_start',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début de licence'),
        ),
    ]
