# Generated by Django 6.0.4 on 2026-05-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='École', max_length=200)),
                ('acronym', models.CharField(blank=True, help_text="Sigle de l'école", max_length=20)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/')),
                ('director_signature', models.ImageField(blank=True, null=True, upload_to='school/')),
                ('director_name', models.CharField(blank=True, max_length=200)),
                ('academic_year', models.CharField(default='2024-2025', max_length=9)),
                ('primary_color', models.CharField(default='#1e40af', help_text='Couleur primaire (hex)', max_length=7)),
                ('secondary_color', models.CharField(default='#3b82f6', help_text='Couleur secondaire (hex)', max_length=7)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Guinée', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Information de l'école",
                'verbose_name_plural': "Informations de l'école",
            },
        ),
    ]
