# Generated by Django 6.0.4 on 2026-06-02 15:31

from django.db import migrations


def seed_academic_years(apps, schema_editor):
    AcademicYear = apps.get_model('school', 'AcademicYear')
    AcademicYear.objects.get_or_create(name='2024-2025', defaults={'is_active': True})


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_academicyear'),
    ]

    operations = [
        migrations.RunPython(seed_academic_years),
    ]
