# Generated by Django 6.0.6 on 2026-06-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
