# Generated by Django 6.0.6 on 2026-06-30 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_academicyear_archived'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_info', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.CharField(help_text='Ex: 2024-2025', max_length=9),
        ),
        migrations.AlterUniqueTogether(
            name='schoolinfo',
            unique_together={('tenant', 'id')},
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_academic_year_per_tenant'),
        ),
    ]
