# Generated by Django 6.0.4 on 2026-05-02 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('academic_year', models.CharField(default='2024-2025', max_length=9)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('name', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='StudentAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='averages', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_averages', to='grades.term')),
            ],
            options={
                'unique_together': {('student', 'term')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Devoir 1')),
                ('homework2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Devoir 2')),
                ('homework3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Devoir 3')),
                ('composition', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Composition')),
                ('max_score', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
                ('teacher_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='subjects.teachersubject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.term')),
            ],
            options={
                'unique_together': {('student', 'teacher_subject', 'term')},
            },
        ),
    ]
