# Generated by Django 6.0.5 on 2026-05-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_gradehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='homework3',
        ),
    ]
