# Generated by Django 6.0.6 on 2026-06-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_remove_grade_homework3'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
