# Generated by Django 6.0.4 on 2026-05-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_academic_year',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
