# Generated by Django 6.0.5 on 2026-06-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_options_userprofile_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
