# Generated by Django 6.0.5 on 2026-06-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('permissions', models.JSONField(blank=True, default=list, help_text="Liste des modules accessibles. Utilisez ['*'] pour tout accès.")),
                ('is_system', models.BooleanField(default=False, help_text='Les rôles système ne peuvent pas être supprimés')),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
            },
        ),
    ]
