# Generated by Django 6.0.6 on 2026-06-30 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_role'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='tenants.tenant'),
        ),
    ]
