# Generated by Django 6.0.6 on 2026-07-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_activitylog_tenant_loginattempt_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='secretaire', max_length=50),
        ),
    ]
