# Generated by Django 6.0.6 on 2026-07-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_role_tenant_alter_role_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='primary_color',
            field=models.CharField(default='#1e40af', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secondary_color',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
    ]
