# Generated by Django 6.0.4 on 2026-05-12 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='Mois (YYYY-MM)', max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-month', 'teacher'],
                'unique_together': {('teacher', 'month')},
            },
        ),
    ]
