# Generated by Django 6.0.5 on 2026-06-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_salaryhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
