# Generated by Django 6.0.6 on 2026-06-30 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_matricule'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryhistory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='matricule',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('matricule', 'tenant')},
        ),
    ]
