# Generated by Django 6.0.5 on 2026-06-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment', 'Paiement'), ('attendance', 'Absence'), ('grade', 'Note'), ('composition', 'Composition'), ('general', 'Général')], max_length=20),
        ),
    ]
