# Generated by Django 6.0.5 on 2026-06-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment', 'Paiement'), ('attendance', 'Absence'), ('grade', 'Note'), ('composition', 'Composition'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('general', 'Général')], max_length=20),
        ),
    ]
