# Generated by Django 6.0.4 on 2026-05-12 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Couleur hexadécimale', max_length=7),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('obligatoire', 'Obligatoire'), ('optionnelle', 'Optionnelle')], default='obligatoire', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_subjects', to='teachers.teacher'),
        ),
    ]
