# Generated by Django 6.0.4 on 2026-05-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_color_subject_subject_type_subject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='specialty',
            field=models.CharField(blank=True, choices=[('none', 'Toutes séries'), ('maths', 'Sciences Mathématiques'), ('experimental', 'Sciences Expérimentales'), ('sociales', 'Sciences Sociales'), ('lettres', 'Lettres')], default='none', help_text='Série lycée (none = toutes séries)', max_length=20),
        ),
    ]
