# Generated by Django 6.0.5 on 2026-05-18 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('orange', 'Orange Money'), ('mtn', 'MTN Mobile Money')], max_length=20, unique=True)),
                ('api_key', models.CharField(help_text='Clé API du fournisseur', max_length=255)),
                ('api_secret', models.CharField(blank=True, help_text='Secret API (si applicable)', max_length=255)),
                ('base_url', models.URLField(help_text="URL de base de l'API (ex: https://api.orange.com)")),
                ('callback_url', models.URLField(blank=True, help_text='URL de callback pour les webhooks')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobilePaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='ID de transaction du fournisseur', max_length=100, unique=True)),
                ('phone_number', models.CharField(help_text='Numéro de téléphone du payeur', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Succčs'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('provider_response', models.JSONField(blank=True, help_text='Réponse brute du fournisseur', null=True)),
                ('callback_data', models.JSONField(blank=True, help_text='Données reçues via webhook', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_transaction', to='payments.payment')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='mobile_payments.mobilepaymentprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
